[package]
name = "yamux"
version = "0.4.5"
authors = ["Parity Technologies <admin@parity.io>"]
license = "Apache-2.0 OR MIT"
description = "Multiplexer over reliable, ordered connections"
keywords = ["network", "protocol"]
categories = ["network-programming"]
repository = "https://github.com/paritytech/yamux"
readme = "README.md"
edition = "2018"

[dependencies]
futures = { version = "0.3.4", default-features = false, features = ["std"] }
log = "0.4.8"
nohash-hasher = "0.2"
parking_lot = "0.10"
rand = "0.7.2"
static_assertions = "1"

[dev-dependencies]
anyhow = "1"
async-std = "1"
criterion = "0.3"
futures = "0.3.4"
quickcheck = "0.9"

[[bench]]
name = "concurrent"
harness = false

