[package]
name = "yamux"
version = "0.3.0"
authors = ["Parity Technologies <admin@parity.io>"]
license = "Apache-2.0 OR MIT"
description = "Multiplexer over reliable, ordered connections"
repository = "https://github.com/paritytech/yamux"
readme = "README.md"
edition = "2018"

[dependencies]
bytes = "0.4.12"
futures-preview = { version = "0.3.0-alpha.19", features = ["async-await"] }
futures_codec = "0.3"
log = "0.4.8"
nohash-hasher = "0.1.2"
parking_lot = "0.9"
rand = "0.7.2"
smallvec = "0.6.12"
thiserror = "1.0"

[dev-dependencies]
anyhow = "1.0"
async-std = "0.99"
criterion = "0.3"
quickcheck = "0.9"
tokio = "0.2.0-alpha.6"

[[bench]]
name = "concurrent"
harness = false

